# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build cometa-api-v2`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t cometa-api-v2`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system cometa-api-v2 && \
          adduser --system -G cometa-api-v2 cometa-api-v2

COPY dist/cometa-api-v2 cometa-api-v2/
RUN chown -R cometa-api-v2:cometa-api-v2 .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix cometa-api-v2 --omit=dev -f install

CMD [ "node", "cometa-api-v2" ]
